version: 2
builds:
  - id: beegfs_tools
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/thinkparq/beegfs-go/ctl/internal/cmd.Version={{ .Version }}
      - -X github.com/thinkparq/beegfs-go/ctl/internal/cmd.BinaryName=beegfs
      - -X github.com/thinkparq/beegfs-go/ctl/internal/cmd.Commit={{ .Commit }}
      - -X github.com/thinkparq/beegfs-go/ctl/internal/cmd.BuildTime={{ .Date }}
    binary: beegfs
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ctl/cmd/beegfs/main.go
    hooks:
      post:
        # Note post hooks run for each binary so we actually generate the script twice and just
        # overwrite it in place. It should always be the same for arm64 and amd64 so this is fine.
        # However when adding future post hooks ensure this is what you want.
        - sh -c "go run ctl/cmd/beegfs/main.go completion bash > ./dist/beegfs_bashcomp"

nfpms:
  - id: beegfs_tools
    package_name: beegfs-tools
    file_name_template: "beegfs-tools-{{ .Version }}-{{ .Os }}.{{ .Arch }}"
    vendor: "ThinkparQ GmbH"
    homepage: https://www.beegfs.io
    maintainer: BeeGFS Maintainers <packages@beegfs.com>
    description: A collection of tools for managing BeeGFS.
    provides:
      - beegfs
    license: BeeGFS EULA
    formats:
      - rpm
      - deb
    scripts:
      preinstall: ./build/preinstall.sh
      postinstall: ./build/postinstall.sh
    # Note binaries built above are added to bindir automatically. We use preinstall/postinstall
    # scripts to customize ownership and permissions including adding the setgid bit to the beegfs
    # binary so it runs with group permissions needed to access config files under /etc/beegfs.
    bindir: "/opt/beegfs/sbin/"
    contents:
      - src: /opt/beegfs/sbin/beegfs
        dst: /usr/sbin/beegfs
        type: "symlink"
      - src: ./dist/beegfs_bashcomp
        dst: /etc/bash_completion.d/beegfs
      - src: NOTICE.md
        dst: /usr/share/doc/beegfs-tools/NOTICE.md
      - src: LICENSE.md
        dst: /usr/share/doc/beegfs-tools/LICENSE.md
    rpm:
      signature:
        key_file: "{{ .Env.GPG_KEY_PATH }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

signs:
  - artifacts: checksum
    cmd: gpg2
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
