[[remote_storage_target]]
id = "1"
name = "rst1"
policies = { localflock = true, remoteflock = true, keepdirstructure = true, keepbeegfsmetadata = true }
s3.bucket = "s3bucket"
s3.region = "s3region"


[[remote_storage_target]]
id = "2"
name = "rst2"
policies = { localflock = true, remoteflock = false, keepdirstructure = false, keepbeegfsmetadata = true }
azure.account = "azure_account"
azure.S3.bucket = "azure_bucket"
azure.S3.region = "azure_region"

[[worker]]
id = "1"
name = "beesync-01"
type = "beesync"
hostname = "localhost"
port = 9050
allowInsecure = true
selfSignedTLSCertPath = ""
maxReconnectBackOff = 60
disconnectTimeout = 30

[[worker]]
id = "2"
name = "beesync-02"
type = "beesync"
hostname = "localhost"
port = 9051
allowInsecure = true
selfSignedTLSCertPath = ""
maxReconnectBackOff = 60
disconnectTimeout = 30
