[[remote_storage_target]]
id = "1"
name = "rst1"
policies = { localflock = true, remoteflock = true, keepdirstructure = true, keepbeegfsmetadata = true }
s3.bucket = "s3bucket"
s3.region = "s3region"


[[remote_storage_target]]
id = "2"
name = "rst2"
policies = { localflock = true, remoteflock = false, keepdirstructure = false, keepbeegfsmetadata = true }
azure.account = "azure_account"
azure.S3.bucket = "azure_bucket"
azure.S3.region = "azure_region"
