[[remote_storage_target]]
id = "1"
name = "beemac-minio"
# FastStartMaxSize is the point at which uploads and downloads are split into multiple parts and
# uploaded using a multipart upload. Amazon generally recommends when object sizes approach 100MB, a
# multipart upload should be used instead of uploading the object in a single operation
# (https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html).
policies = { FastStartMaxSize = 104857600 }
s3.endpointUrl = "http://localhost:9000"
# s3.partitionId = "test_partition"
s3.region = "minio"
s3.bucket = "mybucket"
s3.accessKey = "access_key"
s3.secretKey = "secret_key"

[[remote_storage_target]]
id = "2"
name = "oci"
policies = { FastStartMaxSize = 104857600 }
s3.endpointUrl = "https://<ENDPOINT>.compat.objectstorage.<REGION>.oraclecloud.com"
# s3.partitionId = "test_partition"
s3.region = "<REGION>"
s3.bucket = "<BUCKET>"
s3.accessKey = "<ACCESS_KEY>"
s3.secretKey = "<SECRET_KEY>"

[[worker]]
id = "1"
name = "beesync-01"
type = "beesync"
hostname = "localhost"
port = 9011
allowInsecure = false
selfSignedTLSCertPath = "/etc/beegfs/cert.pem"
maxReconnectBackOff = 10
disconnectTimeout = 30
sendRetries = 10
retryInterval = 10
heartbeatInterval = 10

# [[worker]]
# id = "2"
# name = "beesync-02"
# type = "beesync"
# hostname = "localhost"
# port = 9012
# allowInsecure = false
# selfSignedTLSCertPath = "/etc/beegfs/cert.pem"
# maxReconnectBackOff = 60
# disconnectTimeout = 30
