
[log] # Logging configuration cannot be dynamically updated after the application is started.
type = 'stdout'
file = '/var/log/bee-watch.log'
debug = false
incomingEventRate = false

[metadata] # Metadata configuration cannot be dynamically updated after the application is started.
eventLogTarget = '/beegfs/meta_01_tgt_0101/socket/beegfs_eventlog'
eventBufferSize = 10000000
eventBufferGCFrequency = 100000
eventPollFrequency = 1

[[subscriber]] # Subscribers may be updated after the application has started.
type = 'grpc'
id = 1
name = 'test-subscriber'
hostname = 'localhost'
port = '50052'
allow_insecure = true

[[subscriber]]
type = 'grpc'
id = 2
name = 'test2'
hostname = 'host2'
port = '2'
allow_insecure = false

[developer] # Developer configuration cannot be dynamically updated after the application has started.
perfProfilingPort = 0
