# This file provides an example of all possible configuration parameters for BeeWatch.
[log] # Logging configuration cannot be dynamically updated after the application is started except for the log level.
type = 'logfile'
file = '/var/log/beewatch/beewatch.log'
level = 3
maxSize = 1000
numRotatedFiles = 5
incomingEventRate = false
developer = false

[metadata] # Metadata configuration cannot be dynamically updated after the application is started.
eventLogTarget = '/beegfs/meta_01_tgt_0101/socket/beegfs_eventlog'
eventBufferSize = 10000000
eventBufferGCFrequency = 100000

[handler]
maxReconnectBackOff = 60
maxWaitForResponseAfterConnect = 2
pollFrequency = 1

[[subscriber]] # Subscribers may be updated after the application has started.
id = 1
name = 'test-subscriber'
type = 'grpc'
grpcHostname = 'localhost'
grpcPort = '50052'
grpcAllowInsecure = false
grpcDisconnectTimeout = 30     # Time we'll wait after closing our end of the connection for the subscriber to disconnect.
grpcSelfSignedTLSCertPath = ''

[[subscriber]]
id = 2
name = 'test-subscriber2'
type = 'grpc'
grpcHostname = 'localhost'
grpcPort = '50053'
grpcAllowInsecure = false
grpcDisconnectTimeout = 30
grpcSelfSignedTLSCertPath = ''

[[subscriber]]
id = 3
name = 'test-subscriber3'
type = 'grpc'
grpcHostname = 'localhost'
grpcPort = '50054'
grpcAllowInsecure = false
grpcDisconnectTimeout = 30
grpcSelfSignedTLSCertPath = ''

[developer] # Developer configuration cannot be dynamically updated after the application has started.
perfProfilingPort = 0
