name: Check

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
  workflow_call:

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run checks and unit tests
        run: make test
