name: Check

on: [pull_request, workflow_call]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Configure git
        # Make sure the runner has access to the internal repos repo using an access token
        run: git config --global url."https://${{ secrets.CI_PROTOBUF_ACCESS }}@github.com/thinkparq".insteadOf https://github.com/thinkparq
      - name: Install toolchains and tools
        run: make install-tools
      - name: Run checks and unit tests
        run: make test
